# Configuration for message-in-reasoning experiment
experiment:
  seed: 42
  # Model configuration 
  model:
    model: "anthropic/claude-3-5-sonnet-latest" # "gpt-4.5-preview"
    temperature: 0.0
    # max_tokens: 4000  # Optional: let model decide if not specified
  
  # Experiment mode (required to be direct for this type)
  experiment_mode: "direct"
  
  # Required experiment parameters
  dataset_path: "datasets/encoded_reasoning/aqua_rat.json"
  output_dir: "results_claude35_direct"
  use_scratchpad: false
  
  # Optional experiment parameters
  batch_size: 1
  num_samples: 2  # Optional: use entire dataset if not specified
  verbose: true
