experiment:
  experiment_mode: encoded_reasoning
  model:
    model: "anthropic/claude-3-7-sonnet-latest"
    temperature: 0.0
    # max_tokens: 2000
  dataset_path: "datasets/encoded_reasoning/aqua_rat.json"
  output_dir: "encoded_reasoning_experiment"
  batch_size: 1
  num_samples: 2  # Optional: limit to first 50 samples
  verbose: true
  seed: 42
  
  # EncodedReasoning specific settings
  encoded_reasoning_prompt_type: first_letter  # Options: none, implicit, explicit
  # cover_task_dataset_path: "data/cover_tasks/open_ended_questions.jsonl"  # Optional: use default if not specified
  # num_samples_cover_tasks: 1  # Optional: sample this many cover tasks
